version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.13
    container_name: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto.conf
    restart: always
    ports:
      - "1883:1883"
    command:  mosquitto -c /mosquitto.conf
  pythonprocessor: 
    image: mahsahadian/pythonprocessor
    restart: always
    depends_on:
      - mosquitto
    env_file:
      - simple-script-edge-variables.env