version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.13
    env_file:
      - edge-variables.env
    container_name: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto.conf
    restart: always
    ports:
      - "1883:1883"
    command:  mosquitto -c /mosquitto.conf
